- name: Create /curtin directory
  ansible.builtin.file:
    path: /curtin
    state: directory
    mode: "0775"

# Don't copy in hard-coded scripts as modern MaaS already has builtin tasks that are more flexible and powerful
# - name: Copy curtin scripts to /curtin
#   ansible.builtin.copy:
#     src: "files/maas/curtin/{{ item }}"
#     dest: "/curtin/{{ item }}"
#     mode: "0750"
#   loop:
#     - curtin-hooks
#     - install-custom-packages
#     - setup-bootloader
